# Generated by Django 4.2.18 on 2025-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_settings_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ключевые слова для товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
