# Generated by Django 4.2.18 on 2025-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_keywords_en_category_keywords_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('description', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'вопрос/ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужское'), ('female', 'Женское')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
